name: Tomasz Gil
title: Tomasz Gil - frontend developer & graphic designer
description: >
  Jestem programistą front-end, projektuję i tworzę aplikacje internetowe. Zapraszam do kontaktu!
url: "http://tomaszgil.pl"

# Location
source: ./source
destination: ./public
layouts_dir: ./source/layouts
includes_dir: ./includes

# Reading
encoding: "utf-8"
exclude: ["node_modules", "gulpfile.js", "package.json"]
