name: Tomasz Gil

# Location
source: ./source
destination: ./site
layouts_dir: ./source/layouts
includes_dir: ./includes

# Reading
encoding: "utf-8"
exclude: ["node_modules", "gulpfile.js", "package.json"]
